# SPDX-FileCopyrightText: 2025 Imran M <imran@imranmustafa.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 4.2.18 on 2025-02-28 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('source', models.TextField()),
                ('name', models.TextField(blank=True)),
                ('inReplyTo', models.URLField(blank=True, editable=False, max_length=256)),
                ('publishedDate', models.DateField(auto_now_add=True)),
                ('publishedTime', models.TimeField(auto_now_add=True)),
                ('updatedDate', models.DateField(auto_now=True)),
                ('updatedTime', models.TimeField(auto_now=True)),
                ('attributedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('cr', 'Create'), ('up', 'Update'), ('de', 'Delete'), ('fo', 'Follow'), ('ac', 'Accept'), ('re', 'Reject'), ('ad', 'Add'), ('re', 'Remove'), ('li', 'Like'), ('an', 'Announce'), ('un', 'Undo')], max_length=2)),
                ('object', models.URLField(max_length=256)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
