# SPDX-FileCopyrightText: 2025 Imran M <imran@imranmustafa.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 4.2.18 on 2025-03-06 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='publishedDate',
        ),
        migrations.RemoveField(
            model_name='object',
            name='publishedTime',
        ),
        migrations.RemoveField(
            model_name='object',
            name='updatedDate',
        ),
        migrations.RemoveField(
            model_name='object',
            name='updatedTime',
        ),
        migrations.AddField(
            model_name='activity',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
