# Generated by Django 4.2.18 on 2025-03-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_object_tomb'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='url_id',
            field=models.URLField(default='asdf'),
            preserve_default=False,
        ),
    ]
